services:
  app:
    build: .
    volumes:
      - .:/app
      - ./test_data:/test_data
      - ./outputs:/outputs
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./test_data:/test_data
volumes:
  postgres_data: