services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
